services:
  front:
    build:
      context: ./ 
    ports:
      - "3000:3000"
    depends_on:
      - campaigns
      - bosses
      - characters
      - classes
      - npcs
      - weapons
      - mongodb
    networks:
      - dnd-network

  bosses:
    build:
      context: ../dnd-back/api_boss
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - MONGODB_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGODB_PASS=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_HOST=mongodb
    depends_on:
      - mongodb
    networks:
      - dnd-network

  campaigns:
    build:
      context: ../dnd-back/api_campaign
    ports:
      - "8001:8001"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - MONGODB_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGODB_PASS=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_HOST=mongodb
    depends_on:
      - mongodb
      - characters
    networks:
      - dnd-network

  characters:
    build:
      context: ../dnd-back/api_character
    ports:
      - "8002:8002"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - MONGODB_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGODB_PASS=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_HOST=mongodb
    depends_on:
      - mongodb
    networks:
      - dnd-network

  classes:
    build:
      context: ../dnd-back/api_class
    ports:
      - "8003:8003"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - MONGODB_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGODB_PASS=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_HOST=mongodb
    depends_on:
      - mongodb
    networks:
      - dnd-network

  npcs:
    build:
      context: ../dnd-back/api_npc
    ports:
      - "8004:8004"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - MONGODB_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGODB_PASS=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_HOST=mongodb
    depends_on:
      - mongodb
    networks:
      - dnd-network

  weapons:
    build:
      context: ../dnd-back/api_weapon
    ports:
      - "8005:8005"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - MONGODB_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGODB_PASS=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_HOST=mongodb
    depends_on:
      - mongodb
    networks:
      - dnd-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - dnd-network

networks:
  dnd-network:
    driver: bridge
